### ISSUE TITLE
Mask 'Y.0.0' when there is only a  '2.0.1' version and no '2.0.0' version

### ISSUE THREAD

**Issue by paulortman** [dropseedlabs/version-filter#15]
Provide deterministic and documented behavior where a specific version does not exist in a mask.

e.g.

```
current version = '1.0.0'
mask = 'Y.0.0'
versions = [ '1.0.0', '2.0.1', '2.0.2']
```

What version should be returned? '2.0.0' is missing, so the mask will never match.  If we special case the 'Y.0.0' mask, should we return '2.0.1' or '2.0.2'?   This is often, though not exclusively a "startup issue" that will likely occur less often once the current version is more up-to-date.

**Comment by Hypnosphi** [comment]
Actually, I'd like to have a mask with "latest on other major" semantics. So that with `[ '1.0.0', '2.0.0', '2.0.1']` range it would match `2.0.1` if the current version is `1.0.0`, and nothing otherwise.

**Comment by Hypnosphi** [comment]
Maybe some additional extension should be introduced, something like `U` for update (matches anything above the current value). That way, the needed mask would be just `U.Y.Y`

**Comment by paulortman** [comment]
It seems to me that we should introduce a "fuzzy next" modifier to a mask.  In talking with @davegaeddert we were thinking the '-' prefix might work. It would also the mask to match the "next closest" to the mask in the list of those checked.

```python
current_version = '1.0.0'
mask = '-Y.0.0'
versions = ['1.0.0', '2.0.1', '2.0.2', '2.1.0', '3.0.0', '3.0.1', '4.1.1']
```
would match `['2.0.1', '3.0.0', '4.1.1']`

It would work by looking at the "next closest' versions of a generated set of "virtual versions".  In the above example we'd generate a virtual version for all major versions > current version ([2,3,4]) along with fixed '0.0' part, giving us ['2.0.0', '3.0.0', '4.0.0']  When inserted into the ordered versions list, the next closest versions are found.  The result is the union of this set (['2.0.1', '3.0.0', '4.1.1']) with that of the base mask (['3.0.0']) yielding ['2.0.1', '3.0.0', '4.1.1'].

@Hypnosphi Would this do what you want?  I couldn't quite wrap my head around what "latest on other major" would mean differently than "Y.Y.Y"?  I'm probably only seeing this problem through the lens of our use-case, and not understanding what your use case is.

**Comment by Hypnosphi** [comment]
> Would this do what you want

Ideally, I'd like to get `['2.1.0', '3.0.1', '4.1.1']`. Just `4.1.1` would also be OK though

> I couldn't quite wrap my head around what "latest on other major" would mean differently than "Y.Y.Y"

`Y.Y.Y` would match `1.0.0`, which I don't need (it's covered by another mask, `L.Y.Y`).

My usecase is keeping npm dependencies up to date using dependencies.io. For minor and patch updates (`L.Y.Y`), we want a batch PR. For major updates (currently `Y.0.0`), we need separate PRs as each of them requires close review and probably some migration steps.

**Comment by Hypnosphi** [comment]
Looks like dependencies.io does the job of picking the latest version from the range returned by `version-filter` (@davegaeddert please correct me if I'm wrong). Given that, it would be enough to pick everything that has major version above the current one (that is, `['2.0.1', '2.0.2', '2.1.0', '3.0.0', '3.0.1', '4.1.1']`)

**Comment by paulortman** [comment]
Closed by #17

**Comment by Hypnosphi** [comment]
Here's why it doesn't solve the original issue: https://github.com/dropseed/version-filter/blob/aa92b651f42f57580dd6f2a4f90d6de5f5a5b686/tests/test_version_filter.py#L626

I need the versions from current major to be excluded, otherwise I'd just use `Y.Y.Y`

**Comment by paulortman** [comment]
Ah yes, that result deserves an explanation in the comments, but didn't get one.  '1.1.0' only shows up in that list because the current_version (1.0.0) isn't in the list of versions.  It's as though the mask is being run without a current version and thus 1.0.0 is the first anticipated version, it isn't there and thus 1.1.0 is in the list of available versions.  Tests test_next_best_specitemmask_matching_versions_yes3 and test_next_best_specitemmask_matching_versions_yes5 probably show your desired behavior better.

**Comment by paulortman** [comment]
@Hypnosphi re-reading your use case makes me realize I did not successfully address your issue here, though I believe this original issue is resolved.  I think I have a potential issue identified as #18 that would allow the use the existing syntax and do what you actually want.  Sorry I did such a poor job of understanding you in the first place.
