### ISSUE TITLE
Semver Range Operators are unused with masks containing 'Y'

### ISSUE THREAD

**Issue by paulortman** [dropseedlabs/version-filter#18]
* version-filter version: 0.6.0
* Python version: 3
* Operating System:

### Description

Was attempting to select all versions greater than anything in the current major using the mask
'>L.Y.Y' and realized the '>' is completely and quietly ignored.

### What I Did

```python
def test_Hypnosphi_1():
    versions = [
        '1.0.0',
        '1.0.1',
        '1.1.0',
        '1.2.0',
        '2.0.1',
        '3.0.0',
        '4.0.1'
    ]
    current_version = '1.0.0'
    mask = '>L.Y.Y'
    subset = VersionFilter.semver_filter(mask, versions, current_version)
    assert(3 == len(subset))
    assert('2.0.1' in subset)
    assert('3.0.0' in subset)
    assert('4.0.1' in subset)
```

**Comment by Hypnosphi** [comment]
I believe `1.2.0` satisfies `>1.0.0` (which is a partial case of `1.Y.Y`)

**Comment by paulortman** [comment]
This is impractical and the logic is impossible.  Any time there is a 'Y' in the mask, the modifier/operators need to be ignored (but probably not silently #19). Closing.
