### ISSUE TITLE
Pre-release behavior

### ISSUE THREAD

**Issue by davegaeddert** [dropseedlabs/version-filter#3]
@paulortman can you add some tests around pre-releases (and build metadata?)?

With the mask "L.Y.Y", I would have expected pre-releases to be excluded. Didn't dig deeply but getting this result so am assuming that is not the case:
![image](https://cloud.githubusercontent.com/assets/649496/26428824/4b49bd44-40a9-11e7-9099-2b20ce9d555f.png)

To include pre-releases in the filtered results, I would have expected to use a pattern like "L.Y.Y-Y". Thoughts?

http://semver.org/#spec-item-9

**Comment by davegaeddert** [comment]
Actually, I'll make sure I'm not missing something on my end but with an installed version of 0.9.5 and a mask of "L.Y.Y", the 1.0.0 versions shouldn't have been in that list at all...?

**Comment by paulortman** [comment]
Entirely reasonable request, but it seems like it may be a surprisingly big lift.  I'll see what I can do.

**Comment by paulortman** [comment]
closed by #4

**Comment by paulortman** [comment]
@davegaeddert Also released 0.2.0 with this fix
