### ISSUE TITLE
"v" version prefixes

### ISSUE THREAD

**Issue by davegaeddert** [dropseedlabs/version-filter#5]
Related to #1, should this library support handling a version prefixed by a "v"? e.g. "v1.0.1" interpreted as "1.0.1"

@paulortman does that make sense to add or is it getting outside the scope? node-semver says they strip of any leading "=" or "v": https://docs.npmjs.com/misc/semver#versions

**Comment by paulortman** [comment]
@davegaeddert I suppose this falls into the first half of the maxim: "Be liberal in what you accept and conservative in what you produce"
