### ISSUE TITLE
"L" and "Y" case sensitivity

### ISSUE THREAD

**Issue by davegaeddert** [dropseedlabs/version-filter#9]
Not sure if this will come up or not, but with user input I expect that it might. Do we also want to allow "l" and "y"?

**Comment by paulortman** [comment]
This can certainly be done, but my own bias is to keep it upper case partially because 'l' and '1' are just too similar, but whatever.... "be liberal in what you accept'

**Comment by davegaeddert** [comment]
That's what I was thinking too. I'm good to leave it as is for now...can deal with it if it comes up.
